### ISSUE TITLE
add_predicted_draws not working

### ISSUE THREAD

**Issue by dibatti5** [mjskay/tidybayes.rethinking#12]
The following code from the vignette example:

 ABC %>%
    data_grid(condition) %>%
    add_predicted_draws(m) %>%
    ggplot(aes(x = .prediction, y = condition)) +
    stat_slab()

produces:" Error in inherits(model, "map") : 
  argument "model" is missing, with no default"

nb: 'm' is the Ulam object created from running the Ulam from the rethinking package as per the vignette example. There have been no deviations from the vignette code or library dependencies.

**Comment by mjskay** [comment]
ah thanks! Yes this would be due to changes in tidybayes 3.0 that I haven't propagated to tidybayes.rethinking yet. I will fix it.

**Comment by mjskay** [comment]
this should be fixed now.

**Comment by dibatti5** [comment]
Great! Thank you for looking into this!

Alex


Alex Di Battista, Ph.D
University of Toronto & DRDC Toronto
Toronto, Ontario, Canada
