### ISSUE TITLE
tidy_link() fails for class ulam models

### ISSUE THREAD

**Issue by kmiddleton** [mjskay/tidybayes.rethinking#3]
The updated version of rethinking (>2.0) uses `ulam()` instead of `map2stan()`, yielding objects of class "ulam". This causes `tidy_link()` to fail with the error

``` 
Error in as.data.frame.default(data) : 
  cannot coerce class ‘structure("ulam", package = "rethinking")’ to a data.frame 
```

when `data` is not supplied. This is puzzling, because the traceback located the error at line 86 of tidy_link_sim.R, where the fit data is converted to data.frame. Yet `as.data.frame(fit@data)` works fine.

I am using the following versions:

- tidybayes.rethinking_0.12.0.9000
- tidybayes_2.0.3 
- rethinking_2.01

A full reproducible example is below.

```
library(tidyverse)
library(rethinking)
library(tidybayes)
library(tidybayes.rethinking)

set.seed(3207)

n <- 30

d <- data.frame(d = c(rbinom(n = n, size = 1, prob = 0.2),
                      rbinom(n = n, size = 1, prob = 0.6)),
                grp = rep(1L:2L, each = n))

d %>% 
  group_by(grp) %>% 
  summarize(mean(d))

fit <- ulam(
  alist(
    d ~ bernoulli(p),
    logit(p) <- a_grp[grp],
    a_grp[grp] ~ normal(0, 1.5)
  ),
  data = d
)

tidy_link(fit)
as.data.frame(fit@data)
```

**Comment by mjskay** [comment]
Thanks! Yeah, I haven't updated tidybayes.rethinking in some time. I need to update it to use the new function names from tidybayes as well. Might try to do that this summer.

**Comment by mjskay** [comment]
Support for the new rethinking package should be working now. Some notes:

- `tidy_link()` is deprecated in favor of `add_fitted_draws()`
- `tidy_sim()` is deprecated in favor of `add_predicted_draws()`

There is also a new rethinking-specific vignette that shows how to use `tidybayes` / `tidybayes.rethinking` / `rethinking` together: https://mjskay.github.io/tidybayes.rethinking/articles/tidy-rethinking.html
